module ApplicationHelper
  require 'rqrcode'

  def qr_code(text)
    qr = RQRCode::QRCode.new(text)
    qr.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 4
    ).html_safe
  end

  MEMBERS = [
    {
      "f_name": "Михаил",
      "m_name": "Николаевич",
      "l_name": "Вишнев",
      "email": "vmn@npp-epb.ru",
      "phone": "+7 (903) 103-00-28",
      "phone_work": "+7 (495) 780-35-98",
      "org": "АО НПП ЭПБ",
      "position": "Зам. генерального директора",
      "site": "https://npp-epb.ru",
    },
    {
      "f_name": "Иван",
      "m_name": "Александрович",
      "l_name": "Дубовцов",
      "email": "dub@npp-epb.ru",
      "phone": "+7 (903) 285-00-51",
      "phone_work": "+7 (495) 780-35-98",
      "org": "АО НПП ЭПБ",
      "position": "Специалист Департамента сертификации и тестирования",
      "site": "https://npp-epb.ru",
    },
    {
      "f_name": "Алексей",
      "m_name": "Анатольевич",
      "l_name": "Жуенчик",
      "email": "gaa@npp-epb.ru",
      "phone": "+7 (926) 691-00-59",
      "phone_work": "+7 (495) 780-35-98",
      "org": "АО НПП ЭПБ",
      "position": "Генеральный директор",
      "site": "https://npp-epb.ru",
    },
    {
      "f_name": "Михаил",
      "m_name": "Михайлович",
      "l_name": "Линьков",
      "email": "lmm@npp-epb.ru",
      "phone": "+7 (925) 734-05-91",
      "phone_work": "+7 (495) 780-35-98",
      "org": "АО НПП ЭПБ",
      "position": "Директор Департамента информационной безопасности",
      "site": "https://npp-epb.ru",
    },
    {
      "f_name": "Григорий",
      "m_name": "Николаевич",
      "l_name": "Григорьев",
      "email": "ggn@npp-epb.ru",
      "phone": "+7 (999) 842-24-80",
      "phone_work": "+7 (495) 780-35-98",
      "org": "АО НПП ЭПБ",
      "position": "Заместитель директора Департамента сертификации и тестирования",
      "site": "https://npp-epb.ru",
    },
    {
      "f_name": "Михаил",
      "m_name": "Юрьевич",
      "l_name": "Старченко",
      "email": "smu@npp-epb.ru",
      "phone": "+7 (901) 590-54-82",
      "phone_work": "+7 (495) 780-35-98",
      "org": "АО НПП ЭПБ",
      "position": "Начальник отдела проектирования Департамента информационной безопасности",
      "site": "https://npp-epb.ru",
    },
    {
      "f_name": "Сергей",
      "m_name": "Юрьевич",
      "l_name": "Соколов",
      "email": "ssu@npp-epb.ru",
      "phone": "+7 (916) 551-87-24",
      "phone_work": "+7 (495) 780-35-98",
      "org": "АО НПП ЭПБ",
      "position": "Руководитель тендерного отдела",
      "site": "https://npp-epb.ru",
    },
    {
      "f_name": "Павел",
      "m_name": "Александрович",
      "l_name": "Захаров",
      "email": "zpa@npp-epb.ru",
      "phone": "+7 (905) 594-68-54",
      "phone_work": "+7 (495) 780-35-98",
      "org": "АО НПП ЭПБ",
      "position": "Руководитель группы Департамента сертификации и тестирования",
      "site": "https://npp-epb.ru",
    },
    {
      "f_name": "Иван",
      "m_name": "Михайлович",
      "l_name": "Евдокухин",
      "email": "eim@npp-epb.ru",
      "phone": "+7 (916) 935-53-46",
      "phone_work": "+7 (495) 780-35-98",
      "org": "АО НПП ЭПБ",
      "position": "Начальник отдела технической защиты Департамента информационной безопасности",
      "site": "https://npp-epb.ru",
    },
    {
      "f_name": "Антон",
      "m_name": "Александрович",
      "l_name": "Харьковский",
      "email": "haa@npp-epb.ru",
      "phone": "+7 (916) 919-36-41",
      "phone_work": "+7 (495) 780-35-98",
      "org": "АО НПП ЭПБ",
      "position": "Менеджер отдела продаж",
      "site": "https://npp-epb.ru",
    },
    {
      "f_name": "Кирилл",
      "m_name": "Константинович",
      "l_name": "Гореликов",
      "email": "gkk@npp-epb.ru",
      "phone": "+7 (910) 088-06-55",
      "phone_work": "+7 (495) 780-35-98",
      "org": "АО НПП ЭПБ",
      "position": "Специалист Департамента сертификации и тестирования",
      "site": "https://npp-epb.ru",
    },

  ]
  # vcard_text = "BEGIN:VCARD\nVERSION:3.0\nN:Clark;Jason\nFN:Jason Clark\nORG:MSU Library\nTITLE:Team Leader/Digital Initiatives Librarian [Associate Professor]\nTEL;TYPE=WORK,VOICE:(406) 994-6801\nEMAIL;TYPE=PREF,INTERNET:jaclark@montana.edu\nURL:http://www.jasonclark.info\nREV:20111013T195243Z\nEND:VCARD"
end
